### ISSUE TITLE
CastManager missing function wakeDevice()

### ISSUE THREAD

**Issue by frietveld** [SamsungDForum/SmartViewSDKCastVideo#2]
SmartViewSDKCastVideo/SmartViewSDKCastVideo_Android/FastCast-Demo/src/com/samsung/multiscreenplayer/controller/AppController.java

Has a call to
`mCastManager.wakeDevice(mac, storedDevice.getUri(),
            WOW_TIMEOUT, new SimpleCallback<Service>() {
                                    @Override
                                    public void run(Service result) {
                                        smartDeviceClicked(result);
                                        wakingDialog.cancel();
                                        mDevicesDialog.dismiss();                                                                               
                                    }
                                });`

Unfortunately the CastManager object has no such function

**Comment by RockingPrafull** [comment]
intended methods are added into CastManager.
Thanks for your feedback.
