### ISSUE TITLE
iOS app Crash when tap the castbutton.

### ISSUE THREAD

**Issue by JackTedo** [SamsungDForum/SmartViewSDKCastVideo#3]
Download and run the iOS code without modification. iOS app Crash when tap the castbutton in the top-right corner. Could you fix it please. error information image attached.
<img width="1440" alt="screen shot 2017-04-11 at 15 23 08" src="https://cloud.githubusercontent.com/assets/27009133/24926943/477cc65c-1ecb-11e7-8595-9d8b1af59d57.png">

**Comment by code17lines** [comment]
Please download latest SDK library and build.
[Smart View SDK Download](http://developer.samsung.com/tv/develop/tools/extension-libraries/smart-view-sdk-download)

**Comment by JackTedo** [comment]
Thanks to littleom very much. The new sdk lib really works. 

I will get a new Samsung smart TV to test in several days but I am not sure if the app support this TV or not.  It seems that Smartview support a limited Samsung smart TV. Why not let Smart View SDK support all new Samsung smart TV so that make things easier?

This issue can be closed. thanks.

**Comment by JackTedo** [comment]
This issue can be closed. thanks.
