### ISSUE TITLE
Model: UN24H4500AFXZASKU Samsung Smart TV can not be found by this app

### ISSUE THREAD

**Issue by JackTedo** [SamsungDForum/SmartViewSDKCastVideo#4]
This app(iOS) can not find this tv:
Samsung - 24" Class (23-5/8" Diag.) - LED - 720p - Smart - HDTV - Black
    Model: UN24H4500AFXZASKU: 8040004

Is this supported TV?

**Comment by ankitsaini3005** [comment]
Hello Jack,
It is hard to verify it just from the model no. Can you please provide a complete screenshot of the page @ settings > support > contact Samsung.

**Comment by ankitsaini3005** [comment]
Hello Jack,
 It is hard to verify it just from the model no. Can you please provide a complete screenshot of the page @ settings > support > contact Samsung.

**Comment by JackTedo** [comment]
![wechatimg2](https://cloud.githubusercontent.com/assets/27009133/25081061/0643c600-2316-11e7-971e-bf7923616287.jpeg)
![wechatimg3](https://cloud.githubusercontent.com/assets/27009133/25081062/06444b2a-2316-11e7-95c8-fad21d069009.jpeg)

I guess it is  2014 : H4500 model that is listed in supported TV list ?

List of support TV models.
    Note
    2016 : K4300, K5300 and above
    2015 : J5500 and above (except J6203)
    2014 : H4500, H5500 and above (except H6003/H6103/H6153/H6201/H6203)

**Comment by monster-mj** [comment]
Hi, @JackTedo 
First of all, thanks your interest SmartViewSDK.
but sorry that your TV  is not supported.(NT-14M)

**Comment by JackTedo** [comment]
Thanks to @monster-mj very much. 

If I want to buy another Samsung smart TV that support SmartViewSDK in Amazon.com online, can I check if the Samsung smart TV suport SmartViewSDK or not without go to settings > support > contact Samsung ?

**Comment by monster-mj** [comment]
Hi, @JackTedo 
Alomst above 15 years TV is supported SmartViewSDK not low specification H/W.
Refer to this guide : http://www.samsung.com/uk/support/skp/faq/1052003
I recommand strongly a product over 5000 of middle number.
 It's better to 2016,2017

> 8000
 This number designates the series. The exact specifications of each series will differ by model but generally the higher the series, the higher the specifications on that model.
>

**Comment by JackTedo** [comment]
Thanks to @monster-mj , got it. Very helpful info.
