### ISSUE TITLE
URL not working

### ISSUE THREAD

**Issue by trinaldi** [SamsungDForum/SmartViewSDKCastVideo#6]
The Smart View SDK link seems to be down.

[Smart View SDK link](http://developer.samsung.com/tv/develop/tools/extension-libraries/smartview-sdk-download)

**Comment by code17lines** [comment]
Thanks for reporting. 
Please Try below... 

[Smart View SDK Download](http://developer.samsung.com/tv/develop/tools/extension-libraries/smart-view-sdk-download)
